alter table CITY drop foreign key if exists FKh87vxgdsg7rlw0ujnq9qupyvi;
alter table CITY drop foreign key if exists FKdwvkshc1cm1ecgy88lx3umpnl;
alter table STATION drop foreign key if exists FKdmxg81bt2ksdtxvqr5qvrrvqw;
alter table STATION drop foreign key if exists FK7m5i4kit876er7rtiw3qxx7oc;
alter table STATION drop foreign key if exists FKl8s21emvhb86aubh7m389hrlo;
alter table USERS drop foreign key if exists FKogvei204bkwyfe2enow9mftjy;
alter table USERS drop foreign key if exists FK3gblpwpmm7u56yo0fff8shblc;
drop table if exists CITY;
drop table if exists STATION;
drop table if exists USERS;
create table CITY (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), DISTRICT varchar(32) not null, NAME varchar(32) not null, REGION varchar(32) not null, CREATED_BY integer, MODIFIED_BY integer, primary key (ID)) engine=InnoDB;
create table STATION (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), APARTMENT varchar(16), HOUSE_NO varchar(16), STREET varchar(32), ZIP_CODE varchar(10), X double precision, Y double precision, PHONE varchar(16), TRANSPORT_TYPE varchar(255) not null, CREATED_BY integer, MODIFIED_BY integer, CITY_ID integer, primary key (ID)) engine=InnoDB;
create table USERS (ID integer not null auto_increment, CREATED_AT datetime(6) not null, MODIFIED_AT datetime(6), PASSWORD varchar(24) not null, USERNAME varchar(24) not null, CREATED_BY integer, MODIFIED_BY integer, primary key (ID)) engine=InnoDB;
alter table USERS add constraint UK_h6k33r31i2nvrri9lok4r163j unique (USERNAME);
alter table CITY add constraint FKh87vxgdsg7rlw0ujnq9qupyvi foreign key (CREATED_BY) references USERS (ID);
alter table CITY add constraint FKdwvkshc1cm1ecgy88lx3umpnl foreign key (MODIFIED_BY) references USERS (ID);
alter table STATION add constraint FKdmxg81bt2ksdtxvqr5qvrrvqw foreign key (CREATED_BY) references USERS (ID);
alter table STATION add constraint FK7m5i4kit876er7rtiw3qxx7oc foreign key (MODIFIED_BY) references USERS (ID);
alter table STATION add constraint FKl8s21emvhb86aubh7m389hrlo foreign key (CITY_ID) references CITY (ID);
alter table USERS add constraint FKogvei204bkwyfe2enow9mftjy foreign key (CREATED_BY) references USERS (ID);
alter table USERS add constraint FK3gblpwpmm7u56yo0fff8shblc foreign key (MODIFIED_BY) references USERS (ID);
